### Deliverable 1: Preprocessing the Data for a Neural Network

In [1]:
from google.colab import files
uploaded = files.upload()

Saving charity_data.csv to charity_data.csv

In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN','NAME','USE_CASE'], axis=1)
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,Association,1,0,N,5000,1
1,T3,Independent,C2000,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Association,1,0,N,5000,0
34297,T5,Independent,C3000,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Co-operative,1,1M-5M,N,36500179,0

In [4]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [5]:
# Look at APPLICATION_TYPE value counts for binning
application_type_counts = application_df.APPLICATION_TYPE.value_counts()
application_type_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Determine which values to replace if counts are less than ...?
replace_application = list(application_type_counts[application_type_counts<1000].index)

# Replace in dataframe
for app in replace_application:
    application_df.APPLICATION_TYPE = application_df.APPLICATION_TYPE.replace(app,"Other")
    
# Check to make sure binning was successful
application_df.APPLICATION_TYPE.value_counts()

T3       27037
Other     2266
T4        1542
T6        1216
T5        1173
T19       1065
Name: APPLICATION_TYPE, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts for binning
classificaion_counts = application_df.CLASSIFICATION.value_counts()
classificaion_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [8]:
# Determine which values to replace if counts are less than ..?
replace_class = list(classificaion_counts[classificaion_counts<5000].index)

# Replace in dataframe
for cls in replace_class:
    application_df.CLASSIFICATION = application_df.CLASSIFICATION.replace(cls,"Other")
    
# Check to make sure binning was successful
application_df.CLASSIFICATION.value_counts()

C1000    17326
Other    10899
C2000     6074
Name: CLASSIFICATION, dtype: int64

In [9]:
from numpy import dtype
# Generate our categorical variable lists
application_cat = application_df.dtypes[application_df.dtypes =="object"].index.tolist()
application_df[application_cat].nunique()

APPLICATION_TYPE          6
AFFILIATION               6
CLASSIFICATION            3
ORGANIZATION              4
INCOME_AMT                9
SPECIAL_CONSIDERATIONS    2
dtype: int64

In [10]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(application_df[application_cat]))

# Add the encoded variable names to the dataframe
encode_df.columns = enc.get_feature_names(application_cat)
encode_df.head()

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,APPLICATION_TYPE_Other,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,AFFILIATION_CompanySponsored,AFFILIATION_Family/Parent,AFFILIATION_Independent,AFFILIATION_National,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [11]:
# Merge one-hot encoded features and drop the originals
application_df = application_df.merge(encode_df,left_index=True, right_index=True).drop(columns=application_cat, axis=1)
# application_df = application_df.drop(application_cat,1)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,AFFILIATION_CompanySponsored,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [12]:
# Split our preprocessed data into our features and target arrays
y =application_df['IS_SUCCESSFUL'].values 
X = application_df.drop(['IS_SUCCESSFUL'], axis=1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test= train_test_split(X,y,random_state=78)

In [14]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

### Deliverable 2: Compile, Train and Evaluate the Model

In [15]:

# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 80
hidden_nodes_layer2 = 40
hidden_nodes_layer3 = 20

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units= hidden_nodes_layer1, input_dim= number_input_features, activation="relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="tanh"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid")) 

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                2640

 dense_1 (Dense)             (None, 40)                3240

 dense_2 (Dense)             (None, 20)                820

 dense_3 (Dense)             (None, 1)                 21

=================================================================
Total params: 6,721
Trainable params: 6,721
Non-trainable params: 0
_________________________________________________________________

In [16]:
# Import checkpoint dependencies
import os
from tensorflow.keras.callbacks import ModelCheckpoint

# Define the checkpoint path and filenames
os.makedirs("checkpoints/",exist_ok=True)
checkpoint_path = "checkpoints/weights.{epoch:02d}.hdf5"

In [17]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Create a callback that saves the model's weights every epoch
cp_callback = ModelCheckpoint(
    filepath=checkpoint_path,
    verbose=0,
    save_weights_only=True,
    save_freq='epoch',
    period=5)

WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.

In [18]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100,callbacks=[cp_callback], verbose=1)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.5773 - accuracy: 0.7171
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5681 - accuracy: 0.7214
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5665 - accuracy: 0.7228
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5654 - accuracy: 0.7232
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5646 - accuracy: 0.7238
Epoch 6/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5642 - accuracy: 0.7254
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5634 - accuracy: 0.7244
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5636 - accuracy: 0.7249
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5630 - accuracy: 0.7255
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5627 - accuracy: 0.7254
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5628 - accuracy: 0.7250
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5619 - accuracy: 0.7253
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5622 - accuracy: 0.7266
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5619 - accuracy: 0.7265
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5617 - accuracy: 0.7261
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5613 - accuracy: 0.7262
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5614 - accuracy: 0.7255
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5612 - accuracy: 0.7266
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5609 - accuracy: 0.7269
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5610 - accuracy: 0.7267
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5607 - accuracy: 0.7266
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5605 - accuracy: 0.7267
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5605 - accuracy: 0.7259
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5601 - accuracy: 0.7275
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5598 - accuracy: 0.7278
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5604 - accuracy: 0.7279
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5600 - accuracy: 0.7276
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5596 - accuracy: 0.7275
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5598 - accuracy: 0.7276
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5593 - accuracy: 0.7284
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5593 - accuracy: 0.7281
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5594 - accuracy: 0.7282
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5594 - accuracy: 0.7273
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5589 - accuracy: 0.7282
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5590 - accuracy: 0.7280
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5589 - accuracy: 0.7283
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5589 - accuracy: 0.7282
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5589 - accuracy: 0.7280
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5586 - accuracy: 0.7285
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5587 - accuracy: 0.7287
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5586 - accuracy: 0.7284
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5584 - accuracy: 0.7285
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5584 - accuracy: 0.7291
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5583 - accuracy: 0.7287
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5582 - accuracy: 0.7286
Epoch 46/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5582 - accuracy: 0.7291
Epoch 47/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5580 - accuracy: 0.7289
Epoch 48/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5580 - accuracy: 0.7282
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5577 - accuracy: 0.7291
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5581 - accuracy: 0.7286
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5580 - accuracy: 0.7287
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5579 - accuracy: 0.7288
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5578 - accuracy: 0.7289
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5576 - accuracy: 0.7293
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5574 - accuracy: 0.7297
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5575 - accuracy: 0.7295
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5576 - accuracy: 0.7288
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5576 - accuracy: 0.7291
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5573 - accuracy: 0.7290
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5573 - accuracy: 0.7287
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5572 - accuracy: 0.7296
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5573 - accuracy: 0.7284
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5574 - accuracy: 0.7294
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5572 - accuracy: 0.7287
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5574 - accuracy: 0.7291
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5570 - accuracy: 0.7296
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5570 - accuracy: 0.7294
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5571 - accuracy: 0.7297
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5569 - accuracy: 0.7289
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5572 - accuracy: 0.7287
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5572 - accuracy: 0.7289
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5570 - accuracy: 0.7290
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5572 - accuracy: 0.7294
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5568 - accuracy: 0.7294
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5577 - accuracy: 0.7280
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5576 - accuracy: 0.7287
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5572 - accuracy: 0.7291
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5573 - accuracy: 0.7287
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5575 - accuracy: 0.7287
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5573 - accuracy: 0.7290
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5570 - accuracy: 0.7293
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5568 - accuracy: 0.7292
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5569 - accuracy: 0.7292
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5568 - accuracy: 0.7298
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5566 - accuracy: 0.7297
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5575 - accuracy: 0.7288
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5570 - accuracy: 0.7294
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5568 - accuracy: 0.7297
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5566 - accuracy: 0.7294
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5566 - accuracy: 0.7299
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5563 - accuracy: 0.7299
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5565 - accuracy: 0.7296
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5562 - accuracy: 0.7295
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5567 - accuracy: 0.7290
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5567 - accuracy: 0.7291
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5563 - accuracy: 0.7301
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5567 - accuracy: 0.7294
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5572 - accuracy: 0.7293
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5567 - accuracy: 0.7296
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5570 - accuracy: 0.7296

In [19]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5670 - accuracy: 0.7183 - 468ms/epoch - 2ms/step
Loss: 0.5669510960578918, Accuracy: 0.7182507514953613

In [20]:
# Export model to HDF5 file
nn.save("AlphabetSoupCharity_Optimization10.h5")

In [21]:
#Import from colab
files.download("AlphabetSoupCharity_Optimization10.h5")